language: node_js
node_js:
  - "8"

services:
  - docker

addons:
  apt:
    update: true
    packages:
      - docker-ce

cache:
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $HOME/google-cloud-sdk

env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_script:

  # https://gist.github.com/mjackson/5887963e7d8b8fb0615416c510ae8857
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf "$HOME/google-cloud-sdk"; curl https://sdk.cloud.google.com | bash > /dev/null; fi

  # This line is critical. We setup the SDK to take precedence in our
  # environment over the old SDK that is already on the machine.
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud version

  # auth service account
  - echo $GCLOUD_KEY | base64 --decode > gcloud.key
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.key

  # get the cluster credentials
  - gcloud container clusters get-credentials website --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT

  # auth docker
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - echo

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
    #  tags: true
