apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    tier: backend

spec:
  type: NodePort
  selector:
    tier: backend

  ports:
  - protocol: TCP
    port: {{ .Values.ingress.port }}
    targetPort: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    tier: backend

spec:

  selector:
    matchLabels:
      tier: backend

  template:
    metadata:
      labels:
        tier: backend

    spec:
      containers:
      - name: backend
        imagePullPolicy: Always
        image: tomnlittle/website-backend:{{ .Values.tag }}
        ports:
        - name: backend
          containerPort: {{ .Values.backend.port }}

        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.backend.port }}
        #   initialDelaySeconds: 10
        #   periodSeconds: 5

        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.backend.port }}
        #   initialDelaySeconds: 20
        #   periodSeconds: 30
