apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    tier: backend

spec:
  selector:
    tier: backend

  ports:
  - name: backend
    port: 3000
    targetPort: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    tier: backend

spec:

  selector:
    matchLabels:
      tier: backend

  template:
    metadata:
      labels:
        tier: backend

    spec:
      containers:
      - name: backend
        imagePullPolicy: Always
        image:
        ports:
        - name: backend
          containerPort: 3000

        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 30
