apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.ingress.port }}
    targetPort: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend

spec:

  selector:
    matchLabels:
      tier: frontend

  template:
    metadata:
      labels:
        tier: frontend

    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: tomnlittle/website:{{ .Values.frontend.tag }}
        ports:
        - name: frontend
          containerPort: {{ .Values.frontend.port }}
