apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
    namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - secretName: {{ .Values.secrets.name }}
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: frontend
          servicePort: {{ .Values.ingress.port }}
