apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.gcp.kubernetes.io/pre-shared-cert: "website-ingress-secrets"
spec:
  rules:
  - host: www.tomnlittle.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: frontend
          servicePort: {{ .Values.ingress.port }}
  - host: api.tomnlittle.com
    http:
      - path: /*
        backend:
          serviceName: backend
          servicePort: {{ .Values.ingress.port }}
