apiVersion: v1
kind: Service
metadata:
  name: frontend
  # namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend
spec:
  selector:
    tier: frontend
  ports:
  - name: frontend
    port: 3001
    targetPort: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  # namespace: {{ .Release.Namespace }}
  labels:
    tier: frontend

spec:

  selector:
    matchLabels:
      tier: frontend

  template:
    metadata:
      labels:
        tier: frontend

    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: crccheck/hello-world
        ports:
        - name: frontend
          containerPort: 8000
